# ABOUTME: ReadTheDocs configuration file for SimCraft documentation.
# ABOUTME: Specifies build environment, Python version, and Sphinx configuration.

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

formats:
  - pdf
  - epub
